ENH: Improve configuration export for build or install tree
KitwareMedical/IntersonArraySDKCxx pull request #12
Opened 2017-04-21 19:37 UTC by mjallais

This commit updates the buildsystem to allow other projects to include
"IntersonArraySDKCxx" using either its build or install tree.

This means that configuring a project Foo with

  -DIntersonArraySDKCxx_DIR:PATH:/path/to/IntersonArraySDKCxx-build-Release

or

  -DIntersonArraySDKCxx_DIR:PATH:/path/to/IntersonArraySDKCxx-install

will allow

  find_package(IntersonArraySDKCxx REQUIRED)

to work as expected within Foo CMakeLists.txt.

2017-04-24 21:36 UTC, thewtex reviewed
I am confused about `CONF_INCLUDE_DIRS` -- see some questions inline.

2017-04-24 21:36 UTC, thewtex commented on CMakeLists.txt
> +    PATH_VARS CONF_INCLUDE_DIRS
Where is `CONF_INCLUDE_DIRS` set?

2017-04-24 21:36 UTC, thewtex commented on CMakeLists.txt
> -set( CONF_INCLUDE_DIRS
I see `CONF_INCLUDE_DIRS` is removed here.

2017-04-25 13:31 UTC, mjallais commented on CMakeLists.txt
> +    PATH_VARS CONF_INCLUDE_DIRS
It is defined line 39. It was set two times in the previous CMakeLists (l.37 and 90)

2017-04-25 15:08 UTC, thewtex requested changes

2017-04-25 15:08 UTC, thewtex commented on CMakeLists.txt
> +    PATH_VARS CONF_INCLUDE_DIRS
The variable is set to two different values for a build tree an install tree. So, the setting removed on line 90 needs to be added before `# Configure 'IntersonArraySDKCxxConfig.cmake' for an install tree`

2017-05-03 17:42 UTC, jcfr commented
@mjallais thanks for address the comment of @thewtex 

Before integrating, do you confirm that building a project against either clean build tree or clean install now work well ?

2017-05-09 21:08 UTC, mjallais commented
Building a project against either a build tree or an install tree now works well :)

2017-05-09 21:14 UTC, thewtex approved these changes
:1st_place_medal:

2017-05-09 21:14 UTC, merged

2017-05-09 21:19 UTC, jcfr commented
🎆  Well done @mjallais , yet an other example of project illustrating the best practices.