Fix Buffer Size
KitwareMedical/IntersonArraySDKCxx pull request #15
Opened 2017-05-23 13:59 UTC by samuelgerber

The buffer size in the Bmode image was to large. The buffer size is unaffacted
by scanWidth and scanHeight in the ScanConverter and appers to have a fixed size
of NBOLINES x MAX_SAMPLES.

Now teh BMode images is received at full depth and the image size does not ahve to
be set to MAX_SMAPLES/2.

2017-05-23 18:54 UTC, thewtex requested changes
Some cleanup issues noted.

The bufferHeight change is logical.

I'll defer to @aylward, who has the most experience with the code / API.

2017-05-23 18:54 UTC, thewtex commented on src/IntersonArrayCxxImagingContainer.cxx
> +     std::cout << "Conatiner NBOFLINES: " << Container::NBOFLINES << std::endl;
Remove debug code

2017-05-23 18:54 UTC, thewtex commented on src/IntersonArrayCxxImagingContainer.cxx
>    void SetImageSize( int width, int height )
Remove method if it does nothing

2017-05-23 18:54 UTC, thewtex commented on src/IntersonArrayCxxImagingContainer.cxx
> +    //  this->GetHeightScan() );
Remove me

2017-05-23 19:08 UTC, thewtex approved these changes

2017-05-30 18:11 UTC, samuelgerber commented
Since the buffer sizes are fixed should we copy the buffer through memcpy?

Also should we copy the buffer at all or just point to it? The consumer of the buffer will have to do it's own copy in any case, since it will get overwritten when the callback returns and more images are acquired

2017-05-30 18:42 UTC, thewtex commented
The data is being marshaled (moved) from memory in .NET managed runtime to the native C++ runtime, so we need do the move. To be more efficient, we would have to find a `memcpy` or `std::copy` or equivalent that does the marshalling.

2017-05-30 18:49 UTC, samuelgerber commented
https://msdn.microsoft.com/en-us/library/system.runtime.interopservices.marshal.copy(v=vs.110).aspx

2017-05-30 19:09 UTC, thewtex commented
Cool, looks promising.

2017-05-30 19:10 UTC, samuelgerber commented
Or: https://msdn.microsoft.com/en-us/library/1dz8byfh.aspx
if we don't want to do a copy.

2017-06-01 20:15 UTC, thewtex commented
@samuelgerber yes -- the C++/CLI version is what we'll need.

Ping @aylward - any chance to review?

2017-06-01 20:23 UTC, aylward commented
Looks good to me.   pin_ptr - cool!  Learn something new all of the time.   Doing a Copy seems cleaner and less likely to cause future users confusion (since pin_ptr is a rare concept).

2017-06-02 00:46 UTC, samuelgerber commented
Agreed, would open the door for misuse. But probably would increase speed if need.

Merging as is.

2017-06-02 00:46 UTC, merged